# Generated by Django 4.2.6 on 2023-12-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_url",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
