# Generated by Django 4.2.6 on 2023-12-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_api", "0002_order_invoice_url_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktype",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
